/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ModoSombraRouteImport } from './routes/modo-sombra'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as TreinarRouteImport } from './routes/treinar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoSombraRoute = ModoSombraRouteImport.update({
  id: '/modo-sombra',
  path: '/modo-sombra',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarRoute = TreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/resultado': typeof ResultadoRoute
  '/treinar': typeof TreinarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/resultado': typeof ResultadoRoute
  '/treinar': typeof TreinarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/resultado': typeof ResultadoRoute
  '/treinar': typeof TreinarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historico' | '/modo-sombra' | '/resultado' | '/treinar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historico' | '/modo-sombra' | '/resultado' | '/treinar'
  id:
    '__root__' | '/' | '/historico' | '/modo-sombra' | '/resultado' | '/treinar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  ModoSombraRoute: typeof ModoSombraRoute
  ResultadoRoute: typeof ResultadoRoute
  TreinarRoute: typeof TreinarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-sombra': {
      id: '/modo-sombra'
      path: '/modo-sombra'
      fullPath: '/modo-sombra'
      preLoaderRoute: typeof ModoSombraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar': {
      id: '/treinar'
      path: '/treinar'
      fullPath: '/treinar'
      preLoaderRoute: typeof TreinarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  ModoSombraRoute: ModoSombraRoute,
  ResultadoRoute: ResultadoRoute,
  TreinarRoute: TreinarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
