/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ModoSombraRouteImport } from './routes/modo-sombra'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as TreinarRouteImport } from './routes/treinar'
import { Route as DevMotorClinicoRouteImport } from './routes/dev.motor-clinico'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice/speak'
import { Route as ApiVoiceStatusRouteImport } from './routes/api/voice/status'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoSombraRoute = ModoSombraRouteImport.update({
  id: '/modo-sombra',
  path: '/modo-sombra',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarRoute = TreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMotorClinicoRoute = DevMotorClinicoRouteImport.update({
  id: '/dev/motor-clinico',
  path: '/dev/motor-clinico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceStatusRoute = ApiVoiceStatusRouteImport.update({
  id: '/api/voice/status',
  path: '/api/voice/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/historico': typeof HistoricoRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/perfil': typeof PerfilRoute
  '/resultado': typeof ResultadoRoute
  '/treinar': typeof TreinarRoute
  '/dev/motor-clinico': typeof DevMotorClinicoRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/status': typeof ApiVoiceStatusRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/historico': typeof HistoricoRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/perfil': typeof PerfilRoute
  '/resultado': typeof ResultadoRoute
  '/treinar': typeof TreinarRoute
  '/dev/motor-clinico': typeof DevMotorClinicoRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/status': typeof ApiVoiceStatusRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/historico': typeof HistoricoRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/perfil': typeof PerfilRoute
  '/resultado': typeof ResultadoRoute
  '/treinar': typeof TreinarRoute
  '/dev/motor-clinico': typeof DevMotorClinicoRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/status': typeof ApiVoiceStatusRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desempenho'
    | '/historico'
    | '/modo-sombra'
    | '/perfil'
    | '/resultado'
    | '/treinar'
    | '/dev/motor-clinico'
    | '/api/voice/speak'
    | '/api/voice/status'
    | '/api/voice/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desempenho'
    | '/historico'
    | '/modo-sombra'
    | '/perfil'
    | '/resultado'
    | '/treinar'
    | '/dev/motor-clinico'
    | '/api/voice/speak'
    | '/api/voice/status'
    | '/api/voice/transcribe'
  id:
    | '__root__'
    | '/'
    | '/desempenho'
    | '/historico'
    | '/modo-sombra'
    | '/perfil'
    | '/resultado'
    | '/treinar'
    | '/dev/motor-clinico'
    | '/api/voice/speak'
    | '/api/voice/status'
    | '/api/voice/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesempenhoRoute: typeof DesempenhoRoute
  HistoricoRoute: typeof HistoricoRoute
  ModoSombraRoute: typeof ModoSombraRoute
  PerfilRoute: typeof PerfilRoute
  ResultadoRoute: typeof ResultadoRoute
  TreinarRoute: typeof TreinarRoute
  DevMotorClinicoRoute: typeof DevMotorClinicoRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceStatusRoute: typeof ApiVoiceStatusRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-sombra': {
      id: '/modo-sombra'
      path: '/modo-sombra'
      fullPath: '/modo-sombra'
      preLoaderRoute: typeof ModoSombraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar': {
      id: '/treinar'
      path: '/treinar'
      fullPath: '/treinar'
      preLoaderRoute: typeof TreinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/motor-clinico': {
      id: '/dev/motor-clinico'
      path: '/dev/motor-clinico'
      fullPath: '/dev/motor-clinico'
      preLoaderRoute: typeof DevMotorClinicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/status': {
      id: '/api/voice/status'
      path: '/api/voice/status'
      fullPath: '/api/voice/status'
      preLoaderRoute: typeof ApiVoiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesempenhoRoute: DesempenhoRoute,
  HistoricoRoute: HistoricoRoute,
  ModoSombraRoute: ModoSombraRoute,
  PerfilRoute: PerfilRoute,
  ResultadoRoute: ResultadoRoute,
  TreinarRoute: TreinarRoute,
  DevMotorClinicoRoute: DevMotorClinicoRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceStatusRoute: ApiVoiceStatusRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
