/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModoSombraRouteImport } from './routes/modo-sombra'
import { Route as TreinarRouteImport } from './routes/treinar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoSombraRoute = ModoSombraRouteImport.update({
  id: '/modo-sombra',
  path: '/modo-sombra',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarRoute = TreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/treinar': typeof TreinarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/treinar': typeof TreinarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modo-sombra': typeof ModoSombraRoute
  '/treinar': typeof TreinarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modo-sombra' | '/treinar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modo-sombra' | '/treinar'
  id: '__root__' | '/' | '/modo-sombra' | '/treinar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModoSombraRoute: typeof ModoSombraRoute
  TreinarRoute: typeof TreinarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-sombra': {
      id: '/modo-sombra'
      path: '/modo-sombra'
      fullPath: '/modo-sombra'
      preLoaderRoute: typeof ModoSombraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar': {
      id: '/treinar'
      path: '/treinar'
      fullPath: '/treinar'
      preLoaderRoute: typeof TreinarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModoSombraRoute: ModoSombraRoute,
  TreinarRoute: TreinarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
